upstream_tests:
  image: docker.io/node:current
  before_script:
    - npm ci
  script:
    - npm run test:ci
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml


